variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - build
  - publish
  - scan
  - pages

include:
  - project: 'ska-telescope/templates-repository'
    file:
      - 'gitlab-ci/includes/oci-image.gitlab-ci.yml'
      - 'gitlab-ci/includes/docs.gitlab-ci.yml'
      - 'gitlab-ci/includes/release.gitlab-ci.yml'
      - 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
